horas_trab=int(input("Digite a quantidade de horas trabalhadas: "))
valor_hora=float(input("Digite o valor por hora trabalhada: "))
perc_desc=int(input("Digite o percentual de desconto: "))
num_dep=int(input("Digite a quantidade de dependentes: "))
salario_bruto=(horas_trab*valor_hora)
desconto=(salario_bruto*(perc_desc/100))
salario_liq=(salario_bruto-desconto)
salario_liq=(salario_liq+(num_dep*100))
print("O salário a receber é de R${}".format(salario_liq))