comprimento=float(input("Digite o comprimento do paralelepípedo: "))
largura=float(input("Digite a largura do paralelepípedo: "))
altura=float(input("Digite a altura do paralelepípedo: "))
volume=(comprimento*largura*altura)
print("O volume do paralelepípedo é: {}" .format(volume))